package cli

import (
	"fmt"
	"os"
	"strings"
	"sync"

	"github.com/HikaruEgashira/gh-migrate/packages/migration"
	"github.com/HikaruEgashira/gh-migrate/packages/tui"
	"github.com/spf13/cobra"
)

var promptCmd = &cobra.Command{
	Use:   "prompt <text>",
	Short: "Execute Claude Code with a prompt and create a PR",
	Long: `Execute Claude Code with the provided prompt and create a PR.

The title and body of the PR will be automatically generated by the Claude agent.

Examples:
  gh migrate prompt "Add SECURITY.md" --repo owner/repo
  gh migrate prompt "Translate README to English" --repo org/repo1,org/repo2
  gh migrate prompt --prompt-file .claude/commands/add-gitignore.md --repo owner/repo`,
	Args: cobra.MaximumNArgs(1),
	RunE: runPrompt,
}

func init() {
	rootCmd.AddCommand(promptCmd)

	promptCmd.Flags().StringP("repo", "r", "", "Specify repository name (multiple repositories can be specified with comma separation)")
	promptCmd.MarkFlagRequired("repo")
	promptCmd.Flags().BoolP("force", "f", false, "Delete cache and re-fetch")
	promptCmd.Flags().String("open", "", "Open the created PR in the browser")
	promptCmd.Flags().String("with-dev", "", "Open the created PR in github.dev")
	promptCmd.Flags().StringP("workpath", "w", "", "Specify the path of the working directory")
	promptCmd.Flags().String("prompt-file", "", "Read prompt from file (supports .claude/commands/*.md)")
	promptCmd.Flags().Bool("auto-approve", false, "Auto-approve permission requests from Claude Code")
	promptCmd.Flags().String("template", "", "Path to a local PR template file (overrides repository template)")
}

func runPrompt(cmd *cobra.Command, args []string) error {
	// プロンプトテキストの取得
	var promptText string
	if len(args) == 1 {
		promptText = args[0]
	}

	promptFile, _ := cmd.Flags().GetString("prompt-file")
	if promptText == "" && promptFile == "" {
		return fmt.Errorf("either <text> argument or --prompt-file must be provided")
	}

	// オプションの構築
	repo, _ := cmd.Flags().GetString("repo")
	repos := strings.Split(repo, ",")

	workPath, _ := cmd.Flags().GetString("workpath")
	force, _ := cmd.Flags().GetBool("force")
	open, _ := cmd.Flags().GetString("open")
	withDev, _ := cmd.Flags().GetString("with-dev")
	autoApprove, _ := cmd.Flags().GetBool("auto-approve")
	template, _ := cmd.Flags().GetString("template")

	currentPath, _ := os.Getwd()

	ui := tui.Init("gh-migrate prompt")
	defer ui.Done()

	ui.Status(fmt.Sprintf("processing %d repo(s)", len(repos)))

	var wg sync.WaitGroup
	errChan := make(chan error, len(repos))

	for _, r := range repos {
		wg.Add(1)
		go func(r string) {
			defer wg.Done()

			opts := migration.MigrationOptions{
				Repo:        r,
				WorkPath:    workPath,
				Force:       force,
				Open:        open != "",
				WithDev:     withDev != "",
				Mode:        migration.ModePrompt,
				Prompt:      promptText,
				PromptFile:  promptFile,
				AutoApprove: autoApprove,
				Template:    template,
				CurrentPath: currentPath,
			}

			if err := migration.ExecuteMigration(opts, ui); err != nil {
				errChan <- fmt.Errorf("%s: %w", r, err)
			}
		}(r)
	}

	wg.Wait()
	close(errChan)

	for err := range errChan {
		ui.Error("%v", err)
	}

	return nil
}
