name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run gh-migrate
        run: |
          go mod tidy
          go build
          gh extension install .
          gh migrate --help

          prurl=$(gh migrate --repo HikaruEgashira/gh-migrate --cmd "ls" --force | grep 'http')
          echo $prurl
          # gh pr close $prurl
        env:
            GH_TOKEN: ${{ github.token }}

# act push
