name: CI
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run gh-migrate
        run: |
            go mod tidy
            go build
            gh extension install .
            prurl=$(gh migrate --repo HikaruEgashira/gh-migrate --cmd "sed -i '' 's/gh-migrate/gh-migrate2/g' README.md")
            gh pr close $prurl
        env:
            GH_TOKEN: ${{ github.token }}
