name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run gh-migrate
        run: |
          cargo install ast-grep --locked

          go mod tidy
          go build
          gh extension install .
          gh migrate --help

          mkdir work
          gh migrate --repo HikaruEgashira/gh-migrate --workpath work --astgrep ./ast-grep/rules/upgrade-actions-checkout.yml
        env:
          GH_TOKEN: ${{ github.token }}

# act push
